{% set name = "ever-beta" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ever_beta-{{ version }}.tar.gz
  sha256: 93effa723f93f0a6ded71d8f538118fc3b00f571e422bf9f47bed4b025268782

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - prettytable
    - pillow
    - albumentations
    - tensorboard >=1.14
    - tifffile
    - scikit-image
    - matplotlib-base
    - tqdm
    - pandas
    - wandb
    - einops
    - huggingface_hub
    - pytorch

test:
  imports:
    - ever
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Z-Zheng/ever
  summary: A Library for Earth Vision Researcher
  description: A Pytorch-based Python library to simplify the training and inference of the deep learning model in the remote sensing domain.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/Z-Zheng/ever

extra:
  recipe-maintainers:
    - giswqs
